apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: grifadigital

images:
- name: grifa-verso
  newName: grifa-verso
  newTag: 1855be125d34b2f7d97cea18d71ef4711f7ec93f
