apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: grifadigital

images:
- name: goapp
  newName: grifadigital/grifa-verso
  newTag: a5d730608827c6e18d921d6d41bbb5e105bef8e6
- name: grifa-verso
  newName: grifadigital/grifa-verso
  newTag: 4e568d9f0fb89bead5e41e39aaba5b7ab1d52c1d
