apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: grifadigital

images:
- name: goapp
  newName: grifadigital/grifa-verso
  newTag: a5d730608827c6e18d921d6d41bbb5e105bef8e6
- name: grifa-verso
  newName: grifadigital/grifa-verso
  newTag: 4b40e09f4c53aaee564d401b1f3cb92d072acf06
