apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: grifadigital

images:
- name: grifa-verso
  newName: grifadigital/grifa-verso
  newTag: 34723f79615a100b09e62962119d90e7e5c855b3
