name: CD
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: grifadigital
          password: ${{ secrets.DOCKER_PASSWORDS }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: grifadigital/grifa-verso:${{github.sha}}
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: imranismail/setup-kustomize@v1
      - run: |
          kustomize edit set image grifa-verso=grifadigital/grifa-verso:${{github.sha}}
        working-directory: k8s  

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag to `${{github.sha}}`"

      - name: push    
        uses: ad-m/github-push-action@master



       
